## Задание 1: Создание и манипуляции с тензорами (25 баллов)

In [72]:
import torch

### 1.1 Создание тензоров (7 баллов)
```python
# Создайте следующие тензоры:
# - Тензор размером 3x4, заполненный случайными числами от 0 до 1
# - Тензор размером 2x3x4, заполненный нулями
# - Тензор размером 5x5, заполненный единицами
# - Тензор размером 4x4 с числами от 0 до 15 (используйте reshape)
```

In [73]:
tensor_3x4 = torch.rand((3, 4))

tensor_2x3x4 = torch.zeros((2, 3, 4))

tensor_5x5 = torch.ones((5, 5))

tensor_4x4 = torch.arange(0, 16, 1).reshape((4, 4))


print('Тензор размером 3x4, заполненный случайными числами от 0 до 1')
print(tensor_3x4)
print()
print('Тензор размером 2x3x4, заполненный нулями')
print(tensor_2x3x4)
print()
print('Тензор размером 5x5, заполненный единицами')
print(tensor_5x5)
print()
print('Тензор размером 4x4 с числами от 0 до 15')
print(tensor_4x4) 

Тензор размером 3x4, заполненный случайными числами от 0 до 1
tensor([[0.3373, 0.6933, 0.0491, 0.1294],
        [0.6017, 0.6432, 0.9979, 0.8780],
        [0.7082, 0.0616, 0.6069, 0.9395]])

Тензор размером 2x3x4, заполненный нулями
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Тензор размером 5x5, заполненный единицами
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

Тензор размером 4x4 с числами от 0 до 15
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


### 1.2 Операции с тензорами (6 баллов)
```python
# Дано: тензор A размером 3x4 и тензор B размером 4x3
# Выполните:
# - Транспонирование тензора A
# - Матричное умножение A и B
# - Поэлементное умножение A и транспонированного B
# - Вычислите сумму всех элементов тензора A
```

In [74]:
A = torch.rand((3, 4))
B = torch.rand((4, 3))

print('тензор A')
print(A)
print()
print('тензор B')
print(B)
print()

print('Транспонирование тензора A')
print(A.T)
print()
print('Матричное умножение A и B')
print(A @ B)
print()
print('Поэлементное умножение A и транспонированного B')
print(A * B.T)
print()
print('Вычислите сумму всех элементов тензора A')
print(A.sum())


тензор A
tensor([[0.0398, 0.1510, 0.5137, 0.4665],
        [0.3047, 0.6189, 0.0909, 0.1910],
        [0.4286, 0.4688, 0.8270, 0.7251]])

тензор B
tensor([[0.2573, 0.2423, 0.2963],
        [0.5401, 0.5915, 0.2477],
        [0.8957, 0.9859, 0.2702],
        [0.3305, 0.7130, 0.2427]])

Транспонирование тензора A
tensor([[0.0398, 0.3047, 0.4286],
        [0.1510, 0.6189, 0.4688],
        [0.5137, 0.0909, 0.8270],
        [0.4665, 0.1910, 0.7251]])

Матричное умножение A и B
tensor([[0.7061, 0.9380, 0.3012],
        [0.5572, 0.6657, 0.3145],
        [1.3439, 1.7135, 0.6425]])

Поэлементное умножение A и транспонированного B
tensor([[0.0102, 0.0815, 0.4601, 0.1542],
        [0.0738, 0.3661, 0.0896, 0.1362],
        [0.1270, 0.1161, 0.2234, 0.1760]])

Вычислите сумму всех элементов тензора A
tensor(4.8259)


### 1.3 Индексация и срезы (6 баллов)
```python
# Создайте тензор размером 5x5x5
# Извлеките:
# - Первую строку
# - Последний столбец
# - Подматрицу размером 2x2 из центра тензора
# - Все элементы с четными индексами
```

In [75]:
tensor = torch.arange(0, 125, 1).reshape((5, 5, 5))

print('тензор 5x5x5')
print(tensor)
print()

print('Первая строка')
print(tensor[0, :, :])
print()
print('Последний столбец')
print(tensor[:, :, -1])
print()
print('Подматрица размером 2x2x2 из центра тензора')
print(tensor[2:4, 2:4, 2:4])
print()
print('Все элементы с четными индексами')
print(tensor[::2, ::2, ::2])
print()


тензор 5x5x5
tensor([[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24]],

        [[ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49]],

        [[ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74]],

        [[ 75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124]]])

Первая строка
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
  

### 1.4 Работа с формами (6 баллов)
```python
# Создайте тензор размером 24 элемента
# Преобразуйте его в формы:
# - 2x12
# - 3x8
# - 4x6
# - 2x3x4
# - 2x2x2x3
```

In [ ]:
tensor = torch.zeros(24)

print('2x12')
print(tensor.reshape((2, 12)))
print()
print('3x8')
print(tensor.reshape((3, 8)))
print()
print('4x6')
print(tensor.reshape((4, 6)))
print()
print('2x3x4')
print(tensor.reshape((2, 3, 4)))
print()
print('2x2x2x3')
print(tensor.reshape((2, 2, 2, 3)))
print()

2x12
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

3x8
tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

4x6
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

2x3x4
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

2x2x2x3
tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])

